// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwdYDNdRBMJZrVCGnH2wg98ROjnYSvGko',
    appId: '1:1025478402833:web:49979f259480dc6e92a2b0',
    messagingSenderId: '1025478402833',
    projectId: 'project-8860406089180923591',
    authDomain: 'project-8860406089180923591.firebaseapp.com',
    storageBucket: 'project-8860406089180923591.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGzEWYSAGSaK4bT_3ZnUkMc8Hj18pL3XA',
    appId: '1:1025478402833:android:57c0744e2cdf46ba92a2b0',
    messagingSenderId: '1025478402833',
    projectId: 'project-8860406089180923591',
    storageBucket: 'project-8860406089180923591.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQrUztoRaJmiktxZTfQN5OLqCRgx_UmH0',
    appId: '1:1025478402833:ios:667a868cb767549292a2b0',
    messagingSenderId: '1025478402833',
    projectId: 'project-8860406089180923591',
    storageBucket: 'project-8860406089180923591.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQrUztoRaJmiktxZTfQN5OLqCRgx_UmH0',
    appId: '1:1025478402833:ios:667a868cb767549292a2b0',
    messagingSenderId: '1025478402833',
    projectId: 'project-8860406089180923591',
    storageBucket: 'project-8860406089180923591.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwdYDNdRBMJZrVCGnH2wg98ROjnYSvGko',
    appId: '1:1025478402833:web:55ef65c788def05f92a2b0',
    messagingSenderId: '1025478402833',
    projectId: 'project-8860406089180923591',
    authDomain: 'project-8860406089180923591.firebaseapp.com',
    storageBucket: 'project-8860406089180923591.firebasestorage.app',
  );
}
